package rules

var supportedMatcherTypes = map[string]struct{}{
	"body.contains":             {},
	"body.regex":                {},
	"header.contains":           {},
	"header.regex":              {},
	"title.contains":            {},
	"cookie.contains":           {},
	"status.eq":                 {},
	"status.in":                 {},
	"favicon.hash":              {},
	"path.exists":               {},
	"redirect.to":               {},
	"script.src.contains":       {},
	"html.meta.contains":        {},
	"json.key.exists":           {},
	"json.path.eq":              {},
	"server.banner.contains":    {},
	"server.banner.regex":       {},
	"tls.cert.subject.contains": {},
	"tls.cert.issuer.contains":  {},
	"tls.cert.dns.contains":     {},
	"tls.alpn.contains":         {},
}
